using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;


namespace CB4;

[Generator(LanguageNames.CSharp)]
public class BuilderGenerator : IIncrementalGenerator
{
    private const string AttributeName = "BuildableAttribute";
    private const string AttributeNamespace = "Buildable.Attributes";
    private const string BuildableAttributeText = $$"""
        // <auto-generated />
        using System;
        
        namespace {{AttributeNamespace}};
        
        [AttributeUsage(AttributeTargets.Class)]
        internal class {{AttributeName}} : Attribute
        {
            public {{AttributeName}}() {}
        }
        
        """;
    
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(c => c.AddSource($"{AttributeName}.g.cs", BuildableAttributeText));

        var models = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                $"{AttributeNamespace}.{AttributeName}",
                predicate: static (_, _) => true,
                transform: static (syntaxContext, cancellationToken) =>
                {
                    cancellationToken.ThrowIfCancellationRequested();
                    var classSymbol = (INamedTypeSymbol)syntaxContext.TargetSymbol;
                    var properties = classSymbol.GetMembers().OfType<IPropertySymbol>()
                        .Select(p => new BuildableModelProperty(
                            p.Name,
                            p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));

                    return new BuildableModel(
                        classSymbol.ContainingNamespace.ToDisplayString(),
                        syntaxContext.TargetSymbol.Name,
                        properties);
                })
            .Collect();
        
        context.RegisterSourceOutput(
            models,
            static (spc, source) =>
            {
                foreach (var model in source)
                {
                    spc.CancellationToken.ThrowIfCancellationRequested();
                    spc.AddSource($"{model.Name}Builder.g.cs", Emit(model));
                }
            });
    }

    private static string Emit(BuildableModel model)
    {
        var stringBuilder = new StringBuilder();
        var fieldName = $"_{ToCamelCase(model.Name)}";
        var builderName = $"{model.Name}Builder";
        var header = $$"""
            // <auto-generated />
            using System;
            
            namespace {{model.Ns}};
            
            public class {{builderName}}
            {
                private {{model.Name}} {{fieldName}} = new();
                
                public {{model.Name}} Build() => {{fieldName}};
                
                public static implicit operator {{model.Name}}({{builderName}} builder) => builder.Build();
            """;
        var footer = "}";
        
        stringBuilder.AppendLine(header);

        foreach (var property in model.Properties)
        {
            var argumentName = ToCamelCase(property.Name);
            var setter = $$"""
            
                public {{builderName}} With{{property.Name}}({{property.FullyQualifiedType}} {{argumentName}})
                {
                    {{fieldName}}.{{property.Name}} = {{argumentName}};
                    return this;    
                }
            """;
            stringBuilder.AppendLine(setter);
        }
        
        stringBuilder.AppendLine(footer);
        
        return stringBuilder.ToString();
    }
    
    private static string ToCamelCase(string name)
    {
        var firstLetter = name.Substring(0, 1).ToLower();
        var remaining = name.Substring(1);
        return $"{firstLetter}{remaining}";
    }

    private record struct BuildableModel(
        string Ns,
        string Name,
        IEnumerable<BuildableModelProperty> Properties);

    private record struct BuildableModelProperty(
        string Name,
        string FullyQualifiedType);
}
