using System;
using System.Linq;
using System.Text;
using CB4.Extensions;
using CB4.Models;

namespace CB4.Emitters;

internal static class BuilderEmitter
{
    private const string BackingFieldName = "_proxy";
    
    internal static string Emit(BuildableModel model)
    {
        var stringBuilder = new StringBuilder();
        
        stringBuilder.AppendLine(GetHeader(model));
        stringBuilder.AppendLine(GetBuilderConstructors(model));

        foreach (var property in model.Properties)
        {
            stringBuilder.AppendLine(GetSetter(model, property));
        }
        
        stringBuilder.AppendLine(GetBuildMethod(model));
        stringBuilder.AppendLine(GetFooter(model));
        
        return stringBuilder.ToString();
    }

    private static string GetHeader(BuildableModel model)
    {
        var builderName = GetBuilderName(model);
        var proxyName = GetProxyName(model);
        
        return $$"""
            // <auto-generated />
            using System;

            namespace {{model.Ns}};

            public partial class {{builderName}}
            {
                private {{proxyName}} {{BackingFieldName}};
            """;
    }
    
    private static string GetBuildMethod(BuildableModel model)
    {
        return model.ContructorType switch
        {
            ConstructorType.WithoutArguments => GetDefaultConstructor(model),
            ConstructorType.WithArguments => GetArgumentConstructor(model),
            _ => throw new ArgumentOutOfRangeException(nameof(ConstructorType))
        };
    }
    
    private static string GetArgumentConstructor(BuildableModel model)
    {
        var stringBuilder = new StringBuilder();
        var header = $$"""

                public {{model.Name}} Build()
                {
                    return new {{model.Name}}(
            """;
        
        var footer = """
                }
            """;
        
        
        stringBuilder.AppendLine(header);

        var i = 0;
        var count = model.Properties.Count();
        foreach (var property in model.Properties)
        {
            i += 1;
            var content = i < count
                ? $"            {BackingFieldName}.{property.Name},"
                : $"            {BackingFieldName}.{property.Name});";
            stringBuilder.AppendLine(content);
        }

        stringBuilder.AppendLine(footer);
        
        return stringBuilder.ToString();
    }

    private static string GetDefaultConstructor(BuildableModel model)
    {
        var stringBuilder = new StringBuilder();
        var header = $$"""
            
                public {{model.Name}} Build()
                {
                    return new {{model.Name}}
                    {           
            """;
        
        var footer = """
                    };
                }
            """;
        
        
        stringBuilder.AppendLine(header);
        
        foreach (var property in model.Properties)
        {
            stringBuilder.AppendLine($"            {property.Name} = {BackingFieldName}.{property.Name},");
        }

        stringBuilder.AppendLine(footer);
        
        return stringBuilder.ToString();
    }

    private static string GetBuilderConstructors(BuildableModel model)
    {
        var builderName = GetBuilderName(model);
        var argumentName = model.Name.ToCamelCase();
        var proxyName = GetProxyName(model);
        var stringBuilder = new StringBuilder();
        
        var header = $$"""
            
                public {{builderName}}()
                {
                    {{BackingFieldName}} = new();
                }
                
                public {{builderName}}({{model.Name}} {{argumentName}})
                {
                   {{BackingFieldName}} = new {{proxyName}}
                   {
            """;
        
        var footer = """
                };
            }
        """;
        
        
        stringBuilder.AppendLine(header);
        
        foreach (var property in model.Properties)
        {
            stringBuilder.AppendLine($"            {property.Name} = {argumentName}.{property.Name},");
        }

        stringBuilder.AppendLine(footer);
        
        return stringBuilder.ToString();
    }

    private static string GetSetter(BuildableModel model, BuildableModelProperty property)
    {
        var builderName = GetBuilderName(model);
        var argumentName = property.Name.ToCamelCase();
        return $$"""
            
                public {{builderName}} With{{property.Name}}({{property.FullyQualifiedType}} {{argumentName}})
                {
                    {{BackingFieldName}}.{{property.Name}} = {{argumentName}};
                    return this;    
                }
            """;
    }

    private static string GetFooter(BuildableModel model)
    {
        var builderName = GetBuilderName(model);
        
        return $$"""
            
                public static implicit operator {{model.Name}}({{builderName}} builder) => builder.Build();
            }     
            """;
    }
    
    private static string GetBuilderName(BuildableModel model) => $"{model.Name}Builder";
    private static string GetProxyName(BuildableModel model) => $"{model.Name}Proxy";
}
