namespace CB4.Emitters;

internal static class BuildableAttributeEmitter
{
    private const string AttributeNamespace = "Buildable.Attributes";
    internal const string AttributeName = "BuildableAttribute";
    internal const string FullyQualifiedAttributeName = $"{AttributeNamespace}.{AttributeName}";
    
    internal static string Emit()
    {
        return $$"""
            // <auto-generated />
            using System;

            namespace {{AttributeNamespace}};

            [AttributeUsage(AttributeTargets.Class)]
            internal sealed class {{AttributeName}} : Attribute
            {
                public {{AttributeName}}() {}
            }
            """;
        }
}
