using CB4.Models;
using static CB4.Helpers.NamingHelper;

namespace CB4.Emitters;

public static class FactoryEmitter
{
    internal static string Emit(BuildableModel model)
    {
        const string backingFieldName = "_defaultValue";
        var argumentName = backingFieldName.Substring(1); // remove _
        var builderName = GetBuilderName(model);
        
        return $$"""
            // <auto-generated />
            #nullable enable
            using System;

            namespace {{model.Ns}};

            public partial class {{model.FactoryName}}
            {
                private {{model.Name}}? {{backingFieldName}};
                
                public {{model.FactoryName}}()
                {
                    {{backingFieldName}} = null;
                }
                
                public {{model.FactoryName}}({{model.Name}} {{argumentName}})
                {
                    {{backingFieldName}} = {{argumentName}};
                }
                
                public {{builderName}} Create()
                {
                    return {{backingFieldName}} is {{model.Name}} {{argumentName}}
                        ? new {{builderName}}({{argumentName}})
                        : new {{builderName}}();
                }
                
                public {{builderName}} Create({{model.Name}} {{argumentName}})
                {
                    return new {{builderName}}({{argumentName}});
                }
            }
            """;
    }
}
