namespace CB4.Emitters;

internal static class FactoryAttributeEmitter
{
    private const string AttributeNamespace = "CB4.Attributes";
    private const string AttributeName = "FactoryAttribute";
    internal const string FullyQualifiedAttributeName = $"{AttributeNamespace}.{AttributeName}";
    
    internal static string Emit()
    {
        return $$"""
            // <auto-generated />
            using System;

            namespace {{AttributeNamespace}};

            [AttributeUsage(AttributeTargets.Class)]
            internal sealed class {{AttributeName}}<T> : Attribute where T : class
            {
            }
            """;
    }
}
