using System.Text;
using CB4.Extensions;
using CB4.Models;

namespace CB4.Emitters;

internal static class PocoEmitter
{
    internal static string Emit(BuildableModel model)
    {
        var stringBuilder = new StringBuilder();
        var header = GetHeader(model);
        var footer = "}";
        
        stringBuilder.AppendLine(header);

        foreach (var property in model.Properties)
        {
            var setter = GetSetter(model, property);
            stringBuilder.AppendLine(setter);
        }
        
        stringBuilder.AppendLine(footer);
        
        return stringBuilder.ToString();
    }

    private static string GetHeader(BuildableModel model)
    {
        var fieldName = GetBackingFieldName(model);
        var builderName = GetBuilderName(model);
        
        return $$"""
            // <auto-generated />
            using System;

            namespace {{model.Ns}};

            public class {{builderName}}
            {
                private {{model.Name}} {{fieldName}} = new();

                public {{model.Name}} Build() => {{fieldName}};
              
                public static implicit operator {{model.Name}}({{builderName}} builder) => builder.Build();
            """;
    }

    private static string GetSetter(BuildableModel model, BuildableModelProperty property)
    {
        var fieldName = GetBackingFieldName(model);
        var builderName = GetBuilderName(model);
        var argumentName = property.Name.ToCamelCase();
        return $$"""
                public {{builderName}} With{{property.Name}}({{property.FullyQualifiedType}} {{argumentName}})
                {
                    {{fieldName}}.{{property.Name}} = {{argumentName}};
                    return this;    
                }
            """;
    }
    
    private static string GetBackingFieldName(BuildableModel model) => $"_{model.Name.ToCamelCase()}";
    private static string GetBuilderName(BuildableModel model) => $"{model.Name}Builder";
}