using System.Text;
using CB4.Extensions;
using CB4.Models;

namespace CB4.Emitters;

internal static class ProxyEmitter
{
    internal static string Emit(BuildableModel model)
    {
        var stringBuilder = new StringBuilder();
        var header = GetHeader(model);
        const string footer = "}";
        
        stringBuilder.AppendLine(header);

        foreach (var property in model.Properties)
        {
            stringBuilder.AppendLine($"    public {property.FullyQualifiedType} {property.Name} {{ get; set; }}");
        }
        
        stringBuilder.AppendLine(footer);
        
        return stringBuilder.ToString();
    }
    
    private static string GetHeader(BuildableModel model)
    {
        var builderName = GetProxyName(model);
        
        return $$"""
            // <auto-generated />
            using System;

            namespace {{model.Ns}};

            public class {{builderName}}
            {
            """;
    }
    
    private static string GetProxyName(BuildableModel model) => $"{model.Name}Proxy";
}
