using System.Text;
using CB4.Models;

namespace CB4.Emitters;

internal static class ProxyEmitter
{
    internal static string Emit(BuildableModel model)
    {
        var stringBuilder = new StringBuilder();
        var header = GetHeader(model);
        const string footer = """
                }                   
            }
            """;
        
        stringBuilder.AppendLine(header);

        foreach (var property in model.Properties)
        {
            stringBuilder.AppendLine($"        internal {property.FullyQualifiedType} {property.Name} {{ get; set; }}");
        }
        
        stringBuilder.AppendLine(footer);
        
        return stringBuilder.ToString();
    }
    
    private static string GetHeader(BuildableModel model)
    {
        var builderName = $"{model.Name}Builder";
        var proxyName = $"{model.Name}Proxy";
        
        return $$"""
            // <auto-generated />
            using System;

            namespace {{model.Ns}};

            public partial class {{builderName}}
            {
                private struct {{proxyName}}
                {
            """;
    }
}
